spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    # mybatis配置
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

    
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.fzwan.springbootlearn.dao.pojo
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath*:com/fzwan/springbootlearn/dao/mapper/*Mapper.xml